from enum import Enum


class CanonicalStatus(str, Enum):
    PENDING = "PENDING"

    INFO_RECEIVED = "INFO_RECEIVED"
    READY_FOR_PICKUP = "READY_FOR_PICKUP"

    PICKED_UP = "PICKED_UP"

    IN_TRANSIT = "IN_TRANSIT"
    ARRIVED_AT_FACILITY = "ARRIVED_AT_FACILITY"
    DEPARTED_FACILITY = "DEPARTED_FACILITY"
    CUSTOMS_PROCESSING = "CUSTOMS_PROCESSING"

    OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY"

    ARRIVED_AT_PICKUP_POINT = "ARRIVED_AT_PICKUP_POINT"
    DELIVERED_TO_PICKUP_POINT = "DELIVERED_TO_PICKUP_POINT"
    AVAILABLE_FOR_PICKUP = "AVAILABLE_FOR_PICKUP"

    DELIVERED = "DELIVERED"
    PICKED_UP_BY_CUSTOMER = "PICKED_UP_BY_CUSTOMER"

    DELIVERY_ATTEMPT_FAILED = "DELIVERY_ATTEMPT_FAILED"
    ADDRESS_ISSUE = "ADDRESS_ISSUE"
    RECIPIENT_UNAVAILABLE = "RECIPIENT_UNAVAILABLE"
    PICKUP_EXPIRED = "PICKUP_EXPIRED"

    RETURN_INITIATED = "RETURN_INITIATED"
    RETURN_IN_TRANSIT = "RETURN_IN_TRANSIT"
    RETURN_DELIVERED = "RETURN_DELIVERED"

    EXCEPTION = "EXCEPTION"
    LOST = "LOST"
    DAMAGED = "DAMAGED"
    HELD = "HELD"